llm:
  provider: "openai"  # Options: openai, azure, local
  
  openai:
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4o"
    temperature: 0.7
    max_tokens: 2000
    
  azure:
    api_key: "${AZURE_OPENAI_API_KEY}"
    endpoint: "${AZURE_OPENAI_ENDPOINT}"
    deployment_name: "${AZURE_OPENAI_DEPLOYMENT}"
    api_version: "2024-02-15-preview"
    temperature: 0.7
    max_tokens: 2000
    
  local:
    model_path: "${LOCAL_MODEL_PATH}"
    context_size: 4096
    temperature: 0.7
    max_tokens: 2000
    gpu_layers: 35

jarvis:
  name: "Jarvis"
  persona: "advanced AI assistant inspired by Iron Man's JARVIS"
  voice_id: 0
  
weather:
  api_key: "${OPENWEATHERMAP_API_KEY}"
  default_city: "London"
  
wolframalpha:
  api_key: "${WOLFRAMALPHA_API_KEY}"

logging:
  level: "INFO"
  conversation_log: "logs/conversations.log"
  decision_log: "logs/decisions.log"
  mask_sensitive: true
  sensitive_patterns:
    - "api[_-]?key"
    - "password"
    - "token"
    - "secret"
